In [22]:
import ast
import pandas as pd
import numpy as np
import torch
from transformers import AutoTokenizer
from torch.utils.data import Dataset, DataLoader
from torch import Tensor

In [64]:
class CFG:
    """ Pipeline Setting """
    train, test = True, False
    checkpoint_dir = './saved/model'
    resume, load_pretrained,  state_dict = True, False, '/'
    name = 'FBP3_Base_Train_Pipeline'
    loop = 'mpl_loop'
    dataset = 'FBPDataset'  # dataset_class.dataclass.py -> FBPDataset, MPLDataset
    model_arch = 'FBPModel'  # model.model.py -> FBPModel, MPLModel
    model = 'microsoft/deberta-v3-large'
    tokenizer = AutoTokenizer.from_pretrained(model)
    image_pooling = 'MeanPooling'  # mean, attention, max, weightedlayer, concat, conv1d, lstm
    text_pooling = 'MeanPooling'  # mean, attention, max, weightedlayer, concat, conv1d, lstm
    batch_size = 2

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [70]:
test = 'I am very hungry now'
inputs = CFG.tokenizer(
        test,
        truncation=True,
        return_tensors=None,
        add_special_tokens=True,  # later, we will add ourselves
    )
i = 0
inputs['input_ids'][i+1], inputs['input_ids']

(273, [1, 273, 481, 379, 7092, 394, 2])

In [71]:
CFG.tokenizer.sep_token_id

2

In [73]:
tmp1, tmp2 = torch.as_tensor([1,2,3]), torch.as_tensor([4,5,6])
all = tmp1 + tmp2
type(all)

torch.Tensor

In [18]:
test_df = df.iloc[0:48, :]

id   cell_id cell_type  \
0   00001756c60be8  1862f0a6      code   
1   00001756c60be8  2a9e43d6      code   
2   00001756c60be8  038b763d      code   
3   00001756c60be8  2eefe0ef      code   
4   00001756c60be8  0beab1cd      code   
5   00001756c60be8  9a78ab76      code   
6   00001756c60be8  ebe125d5      code   
7   00001756c60be8  d9dced8b      code   
8   00001756c60be8  86497fe1      code   
9   00001756c60be8  e2c8e725      code   
10  00001756c60be8  ff7c44ed      code   
11  00001756c60be8  0e7c906e      code   
12  00001756c60be8  dd0c804a      code   
13  00001756c60be8  781bbf3c      code   
14  00001756c60be8  bd94f005      code   
15  00001756c60be8  62638fba      code   
16  00001756c60be8  bb69e88c      code   
17  00001756c60be8  6b5664c7      code   
18  00001756c60be8  23783525      code   
19  00001756c60be8  8522781a      code   
20  00001756c60be8  8ca8392c      code   
21  00001756c60be8  17ec3fc4      code   
22  00001756c60be8  76512d50      code   
23  00001756c60be8  a98c5d9f      code   
24  00001756c60be8  06365725      code   
25  00001756c60be8  59959af5      code   
26  00001756c60be8  80151ab7      code   
27  00001756c60be8  5bf9ca51      code   
28  00001756c60be8  f5504853      code   
29  00001756c60be8  9f50dca0      code   
30  00001756c60be8  21616367  markdown   
31  00001756c60be8  fcb6792d  markdown   
32  00001756c60be8  63c26fa2  markdown   
33  00001756c60be8  4bb2e30a  markdown   
34  00001756c60be8  a6357f7e  markdown   
35  00001756c60be8  45082c89  markdown   
36  00001756c60be8  77e56113  markdown   
37  00001756c60be8  448eb224  markdown   
38  00001756c60be8  032e2820  markdown   
39  00001756c60be8  8554b284  markdown   
40  00001756c60be8  36002912  markdown   
41  00001756c60be8  ac301a84  markdown   
42  00001756c60be8  23705731  markdown   
43  00001756c60be8  1496beaf  markdown   
44  00001756c60be8  2e1a5949  markdown   
45  00001756c60be8  7e2f170a  markdown   
46  00001756c60be8  bfbde93e  markdown   
47  00001756c60be8  0d136e08  markdown   

                                               source  rank  fold  
0   # This Python 3 environment comes with many he...     0     0  
1   import numpy as np import pandas as pd import ...     2     0  
2    import warnings warnings filterwarnings 'ignore'     4     0  
3           matplotlib rcParams update 'font.size' 14     6     0  
4   def evaluate_preds train_true_values train_pre...     8     0  
5   TRAIN_DATASET_PATH '/kaggle/input/real-estate-...    10     0  
6   train_df pd read_csv TRAIN_DATASET_PATH train_...    14     0  
7                                     train_df dtypes    16     0  
8   num_feat list train_df select_dtypes exclude '...    18     0  
9   test_df pd read_csv TEST_DATASET_PATH test_df ...    20     0  
10  print 'Строк в трейне:' train_df shape 0 print...    22     0  
11                 train_df shape 1 1 test_df shape 1    24     0  
12  submission_df pd read_csv '/kaggle/input/real-...    25     0  
13             train_df 'Id' train_df 'Id' astype str    27     0  
14      train_df num_feat hist figsize 16 16 plt show    29     0  
15                                train_df describe T    31     0  
16  grid sns jointplot train_df 'Rooms' train_df '...    33     0  
17  grid sns jointplot train_df 'KitchenSquare' tr...    34     0  
18  train_df_temp train_df loc train_df 'KitchenSq...    36     0  
19  plt figure figsize 16 8 train_df 'Price' hist ...    39     0  
20  correlation train_df corrwith train_df 'Price'...    41     0  
21  class Data def __init__ self """Константы для ...    43     0  
22  data_inst Data # тренировочные данные data_ins...    45     0  
23  feature_names 'AverageSquareMeterPrice' 'Distr...    47     0  
24  train_df train_df feature_names target_name te...    48     0  
25  final_model CatBoostRegressor silent True lear...    50     0  
26           print f'R2: {round(cv_score.mean(), 3)}'    52     0  
27  feature_importances pd DataFrame zip X columns...

In [55]:
class GoogleAiDataset(Dataset):
    """ Dataset class For Token Classification Pipeline """
    def __init__(self, cfg, df) -> None:
        self.cfg = cfg
        self.df = df
    def __len__(self) -> int:
        return len(self.df)

    def __getitem__(self, item: int):
        tmp = {'input_ids': [1,2,3,4,5,6,6,7,7,5,5,5]}
        return tmp

In [56]:
train_dataset = GoogleAiDataset(CFG, test_df)
loader_train = DataLoader(
            train_dataset,
            batch_size=CFG.batch_size,
            shuffle=True,
            num_workers=0,
            pin_memory=True,
            drop_last=False,
        )

In [63]:
for test in loader_train:
    print(test['input_ids'][1])

tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])
tensor([2, 2])


In [16]:
df = pd.read_csv('perfect_tmp_train.csv')
df

id   cell_id cell_type  \
0        00001756c60be8  1862f0a6      code   
1        00001756c60be8  2a9e43d6      code   
2        00001756c60be8  038b763d      code   
3        00001756c60be8  2eefe0ef      code   
4        00001756c60be8  0beab1cd      code   
...                 ...       ...       ...   
6370642  fffe1d764579d5  0d770d6b  markdown   
6370643  fffe1d764579d5  d45ddc62  markdown   
6370644  fffe1d764579d5  1a63248d  markdown   
6370645  fffe1d764579d5  a8ffc8b4  markdown   
6370646  fffe1d764579d5  4e2d4c2d  markdown   

                                                    source  rank  fold  
0        # This Python 3 environment comes with many he...     0     0  
1        import numpy as np import pandas as pd import ...     2     0  
2         import warnings warnings filterwarnings 'ignore'     4     0  
3                matplotlib rcParams update 'font.size' 14     6     0  
4        def evaluate_preds train_true_values train_pre...     8     0  
...                                                    ...   ...   ...  
6370642                           ## REMOVING THE OUTLIERS    43     4  
6370643                          ### DIMENSIONALITY CURSE     33     4  
6370644                # BANGALORE HOUSE PRICE PREDICTION      0     4  
6370645  * We have achieved 75.2% accuracy in predictin...    69     4  
6370646                                 ## DATA INGESTION      3     4  

[6370647 rows x 6 columns]

In [6]:
test_sequence = 'I am hungry right now'
inputs = CFG.tokenizer.encode_plus(
        test_sequence,
        max_length=4,
        truncation=True,
        return_tensors=None,
        add_special_tokens=False,
    )
inputs

{'input_ids': [273, 481, 7092, 423], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [12]:
inputs['input_ids'] = inputs['input_ids'][1:]

In [13]:
CFG.tokenizer.decode(inputs['input_ids'])

'am hungry right'

In [34]:
""" util function for prompt & dynamic padding """
def adjust_sequences(sequences: list, max_len: int) -> tuple(list, list):
    """
    Reference:
         https://github.com/louis-she/ai4code/blob/master/ai4code/utils.py#L70
    """
    length_of_seqs = [len(seq) for seq in sequences]
    total_len = sum(length_of_seqs)
    cut_off = total_len - max_len
    if cut_off <= 0:
        return sequences, length_of_seqs

    for _ in range(cut_off):
        max_index = length_of_seqs.index(max(length_of_seqs))
        length_of_seqs[max_index] -= 1
    sequences = [sequences[i][:l] for i, l in enumerate(length_of_seqs)]

    return sequences, length_of_seqs


def test_adjust_sequences():
    mock_seqs = [
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 6, 7],
    ]

    sequences, length_of_seqs = adjust_sequences(mock_seqs, 9999)
    print(sequences, length_of_seqs)
    
    sequences, length_of_seqs = adjust_sequences(mock_seqs, 15)
    print(sequences, length_of_seqs)

    sequences, length_of_seqs = adjust_sequences(mock_seqs, 15)
    print(sequences, length_of_seqs)

    sequences, length_of_seqs = adjust_sequences(mock_seqs, 16)
    print(sequences, length_of_seqs)

    sequences, length_of_seqs = adjust_sequences(mock_seqs, 17)
    print(sequences, length_of_seqs)

    sequences, length_of_seqs = adjust_sequences(mock_seqs, 19)
    print(sequences, length_of_seqs)

    sequences, length_of_seqs = adjust_sequences(mock_seqs, 20)
    print(sequences, length_of_seqs)


def longer_tokenizing(cfg, text: str) -> any:
    """
    Tokenize input sentence to longer sequence than common tokenizing
    Append padding strategy NOT Apply same max length, similar concept to dynamic padding
    Truncate longer sequence to match LLM's max sequence
    Args:
        cfg: configuration.CFG, needed to load tokenizer from Huggingface AutoTokenizer
        text: text from dataframe or any other dataset, please pass str type
    Reference:
        https://www.kaggle.com/competitions/AI4Code/discussion/343714
        https://github.com/louis-she/ai4code/blob/master/tests/test_utils.py#L6

    """
    inputs = cfg.tokenizer(
        text,
        max_length=cfg.max_len,
        padding='max_length',
        truncation=True,
        return_tensors=None,
        add_special_tokens=True,
    )
    for k, v in inputs.items():
        inputs[k] = torch.as_tensor(v)
    return inputs

In [31]:
test_adjust_sequences()

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6, 7]] [10, 5, 7]
[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]] [5, 5, 5]
[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]] [5, 5, 5]
[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6]] [5, 5, 6]
[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6]] [6, 5, 6]
[[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6, 7]] [7, 5, 7]
[[1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6, 7]] [8, 5, 7]


In [90]:
""" load dataframe """
df = pd.read_csv('perfect_final_train.csv')
df

id                                            cell_id  \
0       00001756c60be8  ['1862f0a6', '2a9e43d6', '038b763d', '2eefe0ef...   
1       00015c83e2717b  ['c417225b', '51e3cd89', '2600b4eb', '75b65993...   
2       0001bdd4021779  ['3fdc37be', '073782ca', '8ea7263c', '80543cd8...   
3       0001daf4c2c76d  ['86605076', 'df6c939f', '00f87d0a', '986fd4f1...   
4       0002115f48f982  ['18281c6c', 'e3b6b115', '4a044c54', '365fe576...   
...                ...                                                ...   
139251  fffc30d5a0bc46  ['ff1ea6a0', 'a01ce9b3', 'bf92a015', '095812e6...   
139252  fffc3b44869198  ['978a5137', 'faa48f03', '28dfb12a', 'eea2e812...   
139253  fffc63ff750064  ['5015c300', '8238198c', 'f4781d1d', 'b5532930...   
139254  fffcd063cda949  ['7e6266ad', 'd8281fc5', '3e0e4a47', '21387fc8...   
139255  fffe1d764579d5  ['9c3b96a5', '1398a873', 'f71c538e', '8b44a5e8...   

                                                cell_type  \
0       ['code', 'code', 'code', 'code', 'code', 'code...   
1       ['code', 'code', 'code', 'code', 'code', 'code...   
2       ['code', 'code', 'code', 'code', 'code', 'code...   
3       ['code', 'code', 'code', 'code', 'code', 'code...   
4       ['code', 'code', 'code', 'code', 'code', 'code...   
...                                                   ...   
139251  ['code', 'code', 'code', 'code', 'code', 'code...   
139252  ['code', 'code', 'code', 'code', 'code', 'code...   
139253  ['code', 'code', 'code', 'code', 'code', 'code...   
139254  ['code', 'code', 'code', 'code', 'code', 'code...   
139255  ['code', 'code', 'code', 'code', 'code', 'code...   

                                                     rank  \
0       [0, 2, 4, 6, 8, 10, 14, 16, 18, 20, 22, 24, 25...   
1       [4, 5, 6, 7, 8, 9, 12, 15, 16, 17, 18, 21, 22,...   
2              [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 8, 12]   
3       [2, 5, 7, 11, 13, 14, 15, 17, 18, 19, 20, 21, ...   
4                             [1, 2, 3, 4, 5, 6, 7, 8, 0]   
...                                                   ...   
139251  [1, 3, 5, 7, 9, 11, 12, 13, 15, 16, 17, 18, 19...   
139252  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14,...   
139253  [0, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 1...   
139254  [0, 1, 3, 4, 6, 7, 8, 10, 12, 14, 16, 17, 18, ...   
139255  [1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, ...   

                                                   source  fold  
0       ['# This Python 3 environment comes with many ...     0  
1       ['import numpy as np # linear algebra import p...     0  
2       ['import pandas as pd import numpy as np impor...     1  
3       ['# This Python 3 environment comes with many ...     1  
4       ['import numpy as np # linear algebra import p...     2  
...                                                   ...   ...  
139251  ["import warnings warnings filterwarnings 'ign...     4  
139252  ['import matplotlib pyplot as plt import numpy...     0  
139253  ["import numpy as np import pandas as pd impor...     4  
139254  ["import os GPU_id 0 os environ 'CUDA_VISIBLE_...     4  
139255  ["import os for dirname _ filenames in os walk...     4  

[139256 rows x 6 columns]

In [99]:
test_list = df.cell_id.to_numpy()
np.array(ast.literal_eval(test_list[0]))

"['1862f0a6', '2a9e43d6', '038b763d', '2eefe0ef', '0beab1cd', '9a78ab76', 'ebe125d5', 'd9dced8b', '86497fe1', 'e2c8e725', 'ff7c44ed', '0e7c906e', 'dd0c804a', '781bbf3c', 'bd94f005', '62638fba', 'bb69e88c', '6b5664c7', '23783525', '8522781a', '8ca8392c', '17ec3fc4', '76512d50', 'a98c5d9f', '06365725', '59959af5', '80151ab7', '5bf9ca51', 'f5504853', '9f50dca0', '21616367', 'fcb6792d', '63c26fa2', '4bb2e30a', 'a6357f7e', '45082c89', '77e56113', '448eb224', '032e2820', '8554b284', '36002912', 'ac301a84', '23705731', '1496beaf', '2e1a5949', '7e2f170a', 'bfbde93e', '0d136e08', '915643b3', '8ffe0b25', '8a4c95d1', 'b69a4f9b', 'c3ce0945', '3eebeb87', '1ae087ab', 'aaad8355', '503926eb', '3e5f860d']"

In [91]:
test_set = df.iloc[0, :]

pandas.core.series.Series

In [94]:
cell_id_list = ast.literal_eval(test_set.cell_id)
cell_type_list = ast.literal_eval(test_set.cell_type)
rank_list = ast.literal_eval(test_set['rank'])
source_list = ast.literal_eval(test_set.source)

cell_id_list, cell_type_list, rank_list, source_list

(['1862f0a6',
  '2a9e43d6',
  '038b763d',
  '2eefe0ef',
  '0beab1cd',
  '9a78ab76',
  'ebe125d5',
  'd9dced8b',
  '86497fe1',
  'e2c8e725',
  'ff7c44ed',
  '0e7c906e',
  'dd0c804a',
  '781bbf3c',
  'bd94f005',
  '62638fba',
  'bb69e88c',
  '6b5664c7',
  '23783525',
  '8522781a',
  '8ca8392c',
  '17ec3fc4',
  '76512d50',
  'a98c5d9f',
  '06365725',
  '59959af5',
  '80151ab7',
  '5bf9ca51',
  'f5504853',
  '9f50dca0',
  '21616367',
  'fcb6792d',
  '63c26fa2',
  '4bb2e30a',
  'a6357f7e',
  '45082c89',
  '77e56113',
  '448eb224',
  '032e2820',
  '8554b284',
  '36002912',
  'ac301a84',
  '23705731',
  '1496beaf',
  '2e1a5949',
  '7e2f170a',
  'bfbde93e',
  '0d136e08',
  '915643b3',
  '8ffe0b25',
  '8a4c95d1',
  'b69a4f9b',
  'c3ce0945',
  '3eebeb87',
  '1ae087ab',
  'aaad8355',
  '503926eb',
  '3e5f860d'],
 ['code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code',
  'code

In [85]:
""" same as ast.literal_eval() """
cell_id_list = test_set['cell_id'].replace('[', '').replace(']', '').replace('\'', '')
cell_type_list = test_set.cell_type.replace('[', '').replace(']', '').replace('\'', '')
rank_list = test_set['rank'].replace('[', '').replace(']', '').replace('\'', '')
source_list = test_set.source.replace('[', '').replace(']', '').replace('\'', '')

cell_id_list = ''.join(cell_id_list).replace(' ', '').split(',')
cell_type_list = ''.join(cell_type_list).replace(' ', '').split(',')
source_list = ''.join(source_list).replace(' ', '').split(',')
rank_list = list(map(int, ''.join(rank_list).replace(' ', '').split(',')))

cell_id_list, cell_type_list, source_list, rank_list